import { afterEach, expect, it, vi } from 'vitest';
import { connectVideoTapFeedback } from './videoTapFeedback';
afterEach(() => vi.useRealTimers());
it('shows only acknowledged gesture state, then expires', () => {
  vi.useFakeTimers();
  const root = document.createElement('div');
  root.setAttribute('data-paused', '');
  const show = vi.fn();
  const cleanup = connectVideoTapFeedback(root, show);
  root.dispatchEvent(new CustomEvent('will-trigger', { detail: 'toggle:paused' }));
  expect(show).not.toHaveBeenCalledWith('play');
  root.dispatchEvent(new Event('play'));
  expect(show).toHaveBeenLastCalledWith('play');
  vi.advanceTimersByTime(650);
  expect(show).toHaveBeenLastCalledWith(null);
  cleanup();
});
it('ignores seeks, automatic playback, stale requests and disposed listeners', () => {
  vi.useFakeTimers();
  const root = document.createElement('div');
  const show = vi.fn();
  const cleanup = connectVideoTapFeedback(root, show);
  root.dispatchEvent(new CustomEvent('will-trigger', { detail: 'seek:10' }));
  root.dispatchEvent(new Event('play'));
  expect(show).not.toHaveBeenCalled();
  root.dispatchEvent(new CustomEvent('will-trigger', { detail: 'toggle:paused' }));
  root.dispatchEvent(new Event('pause'));
  expect(show).toHaveBeenLastCalledWith('pause');
  root.dispatchEvent(new CustomEvent('will-trigger', { detail: 'toggle:paused' }));
  root.dispatchEvent(new Event('source-change'));
  show.mockClear();
  root.dispatchEvent(new Event('pause'));
  expect(show).not.toHaveBeenCalled();
  cleanup();
  show.mockClear();
  root.dispatchEvent(new CustomEvent('will-trigger', { detail: 'toggle:paused' }));
  root.dispatchEvent(new Event('pause'));
  expect(show).not.toHaveBeenCalled();
});
